[package]
name = "jarvis-security"
version = "0.1.0"
edition = "2021"

[features]
default     = []
intruder    = ["opencv", "chrono"]

[dependencies]
jarvis-core = { path = "../jarvis-core" }
anyhow      = { workspace = true }
tracing     = { workspace = true }
sha2        = "0.10"
hex         = "0.4"
tokio       = { workspace = true }
opencv      = { version = "0.92", features = ["videoio", "objdetect", "imgproc"], optional = true }
chrono      = { version = "0.4", optional = true }
